In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import collections

- Evolución de ventas por volumen y cantidad.
- Estados/ Regiones con mayor cantidad de vendedores.
- Estados/ Regiones con mayor cantidad de compradores.
- Promedio de ventas por estado.
- Dia de la semana y horario con mayor/menor cantidad de ventas.
- Tiempo promedio de demora de entrega por estado.
- Promedio de costo de envió por estado.
- Mes del año con mayor tiempo de demora de entrega.
- Relación entre monto de la compra y medio de pago elegido.
- Medio de pago elegido y evolución en el tiempo por categoría.
- Cantidad de cuotas promedio elegido por categoría.
- TOP de Productos más vendido (por cantidad).
- TOP de productos con mejor reputación.
- TOP de productos ofrecidos por los vendedores.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
customers = pd.read_csv('/content/drive/MyDrive/Archivos olist colab/olist_customers_dataset.csv')
geolocation  = pd.read_csv('/content/drive/MyDrive/Archivos olist colab/olist_geolocation_dataset.csv')
parse_dates = ["shipping_limit_date"]
order_items  = pd.read_csv('/content/drive/MyDrive/Archivos olist colab/olist_order_items_dataset.csv',\
                              infer_datetime_format = True, parse_dates = parse_dates)
parse_dates = ['review_creation_date','review_answer_timestamp']
order_reviews = pd.read_csv('/content/drive/MyDrive/Archivos olist colab/olist_order_reviews_dataset.csv',\
                              infer_datetime_format = True, parse_dates = parse_dates)
order_payments = pd.read_csv('/content/drive/MyDrive/Archivos olist colab/olist_order_payments_dataset.csv')
parse_dates = ['order_purchase_timestamp','order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
orders = pd.read_csv('/content/drive/MyDrive/Archivos olist colab/olist_orders_dataset.csv',\
                              infer_datetime_format = True, parse_dates = parse_dates)
products = pd.read_csv('/content/drive/MyDrive/Archivos olist colab/olist_products_dataset.csv')
sellers = pd.read_csv('/content/drive/MyDrive/Archivos olist colab/olist_sellers_dataset.csv')
product_category = pd.read_csv('/content/drive/MyDrive/Archivos olist colab/product_category_name_translation.csv')
parse_dates = ['won_date']
closed_deals = pd.read_csv('/content/drive/MyDrive/Archivos olist colab/olist_closed_deals_dataset.csv',\
                              infer_datetime_format = True, parse_dates = parse_dates)
parse_dates = ['first_contact_date']
marketing_q = pd.read_csv('/content/drive/MyDrive/Archivos olist colab/olist_marketing_qualified_leads_dataset.csv',\
                              infer_datetime_format = True, parse_dates = parse_dates)

In [ ]:
customers['customer_city'] = customers.customer_city.str.title()
#customers.to_csv(r'C:/Users/notebook/OneDrive/Escritorio/Henry clase/Proyecto grupal OLIST/csv normalizados/CustomersNor.csv', index =False, header=True)

In [ ]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,Sao Bernardo Do Campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,Sao Paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,Mogi Das Cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,Campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,Sao Paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,Taboao Da Serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,Fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,Canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,Cotia,SP

In [ ]:
geolocation["geolocation_city"]=[x.replace('á',"a") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('é',"e") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('í',"i") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('ó',"o") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('ú',"u") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('ã',"a") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('â',"a") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('à',"a") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('ç',"c") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('ê',"e") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('õ',"o") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('ô',"o") for x in geolocation["geolocation_city"]]
geolocation["geolocation_city"]=[x.replace('ü',"u") for x in geolocation["geolocation_city"]]

geolocation['geolocation_city'] = geolocation.geolocation_city.str.title()

#geolocation.to_csv(r'C:/Users/notebook/OneDrive/Escritorio/Henry clase/Proyecto grupal OLIST/csv normalizados/GeolocationNor.csv', index =False, header=True)

In [ ]:
geolocation

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,Sao Paulo,SP
1,1046,-23.546081,-46.644820,Sao Paulo,SP
2,1046,-23.546129,-46.642951,Sao Paulo,SP
3,1041,-23.544392,-46.639499,Sao Paulo,SP
4,1035,-23.541578,-46.641607,Sao Paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,Tapejara,RS
1000159,99900,-27.877125,-52.224882,Getulio Vargas,RS
1000160,99950,-28.071855,-52.014716,Tapejara,RS
1000161,99980,-28.388932,-51.846871,David Canabarro,RS
1000162,99950,-28.070104,-52.018658,Tapejara,RS

In [ ]:
order_items['shipping_limit_date'] = order_items['shipping_limit_date'].dt.date

order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])

#order_items.to_csv(r'C:/Users/notebook/OneDrive/Escritorio/Henry clase/Proyecto grupal OLIST/csv normalizados/Order_itemsNor.csv', index =False, header=True)

In [ ]:
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [ ]:
#df['month'] = df.order_purchase_timestamp.apply(lambda x: x.month).map({1:'Jan',2:'Feb',3:'Mar',4:'Apr',5:'May',6:'Jun',7:'Jul',8:'Aug',9:'Sep',10:'Oct',11:'Nov',12:'Dec'})

In [ ]:
d.resample('Q').mean()

In [ ]:
#order_items ['month_quarter'] =order_items.groupby(order_items['shipping_limit_date'].dt.quarter)
order_items['month_quarter'] = order_items.shipping_limit_date.apply(lambda x: x.quarter)

In [ ]:
df['date'].dt.quarter

In [ ]:
#order_items.drop(columns= 'total_price', inplace=True)

In [ ]:
order_items['Year'] = order_items.shipping_limit_date.apply(lambda x: x.year)

In [ ]:
order_items['total_price'] = order_items['price'] + order_items['freight_value']

In [ ]:
precio_cant=order_items.groupby('Year').agg({'total_price':'sum', 'order_id':'count'})

In [ ]:
precio_cant ['volumen'] = precio_cant['total_price'] * precio_cant['order_id']

In [ ]:
precio_cant

      total_price  order_id       volumen
Year
2016     57183.21       370  2.115779e+07
2017   7000608.86     49765  3.483853e+11
2018   8785262.97     62511  5.491756e+11
2020       498.20         4  1.992800e+03

In [ ]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
 7   month_quarter        112650 non-null  int64
 8   Year                 112650 non-null  int64
 9   total_price          112650 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(3), object(3)
memory usage: 8.6+ MB

In [ ]:
order_items_2018 = order_items[order_items['Year'] == 2018]

In [ ]:
order_items_2018

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,month_quarter,Year,total_price
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,1,2018,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,3,2018,25.78
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75,3,2018,880.75
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65,1,2018,157.60
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,53.99,11.40,3,2018,65.39
...,...,...,...,...,...,...,...,...,...,...
112639,fffb2ef8874127f75b52b643880fd7e0,1,ebceb9726cf5c6187b48e17fe58747b0,609e1a9a6c2539919b8205cf7c4e6ff0,2018-04-09 05:08:33,17.90,22.06,2,2018,39.96
112644,fffbee3b5462987e66fb49b1c5411df2,1,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.85,20.03,2,2018,139.88
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,2,2018,343.40
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,3,2018,386.53
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,2,2018,55.79

In [ ]:
precio_cant_trimestre=order_items_2018.groupby('month_quarter').agg({'total_price':'sum', 'order_id':'count'})

In [ ]:
precio_cant_trimestre

               total_price  order_id       volumen
month_quarter
1               3154467.72     23626  7.452745e+10
2               3390744.19     23299  7.900095e+10
3               2240051.06     15586  3.491344e+10

In [ ]:
precio_cant_trimestre ['volumen'] = precio_cant_trimestre['total_price'] * precio_cant_trimestre['order_id']

In [ ]:
order_payments.drop(order_payments[order_payments.payment_value < 10].index, inplace=True)
order_payments.drop(order_payments[order_payments.payment_value == 13664.08].index, inplace=True)
#order_payments.to_csv(r'C:/Users/notebook/OneDrive/Escritorio/Henry clase/Proyecto grupal OLIST/csv normalizados/Order_paymentsNor.csv', index =False, header=True)

In [ ]:
order_payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [ ]:
order_reviews['review_answer_timestamp'] = order_reviews['review_answer_timestamp'].dt.date

order_reviews['review_answer_timestamp'] = pd.to_datetime(order_reviews['review_answer_timestamp'])

order_reviews['review_comment_title'].fillna('Sin Dato', inplace = True)
order_reviews['review_comment_message'].fillna('Sin Dato', inplace = True)

order_reviews.drop_duplicates(['review_id'], inplace=True)
#order_reviews.to_csv(r'C:/Users/notebook/OneDrive/Escritorio/Henry clase/Proyecto grupal OLIST/csv normalizados/Order_reviewsNor.csv', index =False, header=True)

In [ ]:
order_reviews

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,Sin Dato,Sin Dato,2018-01-18,2018-01-18
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,Sin Dato,Sin Dato,2018-03-10,2018-03-11
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,Sin Dato,Sin Dato,2018-02-17,2018-02-18
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Sin Dato,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Sin Dato,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,Sin Dato,Sin Dato,2018-07-07,2018-07-14
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,Sin Dato,Sin Dato,2017-12-09,2017-12-11
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,Sin Dato,"Excelente mochila, entrega super rápida. Super...",2018-03-22,2018-03-23
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,Sin Dato,Sin Dato,2018-07-01,2018-07-02
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,Sin Dato,"meu produto chegou e ja tenho que devolver, po...",2017-07-03,2017-07-03

In [ ]:
orders['order_purchase_timestamp'] = orders['order_purchase_timestamp'].dt.date
orders['order_approved_at'] = orders['order_approved_at'].dt.date
orders['order_delivered_carrier_date'] = orders['order_delivered_carrier_date'].dt.date
orders['order_delivered_customer_date'] = orders['order_delivered_customer_date'].dt.date
orders['order_estimated_delivery_date'] = orders['order_estimated_delivery_date'].dt.date

orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'])
orders['order_delivered_carrier_date'] = pd.to_datetime(orders['order_delivered_carrier_date'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

#orders.to_csv(r'C:/Users/notebook/OneDrive/Escritorio/Henry clase/Proyecto grupal OLIST/csv normalizados/OrdersNor.csv', index =False, header=True)

In [ ]:
orders

In [ ]:
orders.groupby(['Year']).count()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
Year,,,,,,,,
2016,329,329,329,329,323,281,272,329
2017,45101,45101,45101,45101,45029,43957,43426,45101
2018,54011,54011,54011,54011,53929,53420,52778,54011

In [ ]:
#orders.order_purchase_timestamp.max()

Timestamp('2018-10-17 00:00:00')

In [ ]:
orders['Year'] = orders.order_purchase_timestamp.apply(lambda x: x.year)

In [ ]:
products['product_category_name'].fillna('Sin Dato', inplace = True)
products['product_name_lenght'].fillna(0.0, inplace = True)
products['product_description_lenght'].fillna(0.0, inplace = True)
products['product_photos_qty'].fillna(0.0, inplace = True)
products['product_weight_g'].fillna(0.0, inplace = True)
products['product_length_cm'].fillna(0.0, inplace = True)
products['product_height_cm'].fillna(0.0, inplace = True)
products['product_width_cm'].fillna(0.0, inplace = True)

products['product_category_name'] = products.product_category_name.str.title()

products[['product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']].astype(float)

#products.to_csv(r'C:/Users/notebook/OneDrive/Escritorio/Henry clase/Proyecto grupal OLIST/csv normalizados/ProductsNor.csv', index =False, header=True)

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...
32946,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [ ]:
sellers['seller_city'] = sellers.seller_city.str.title()
#sellers.to_csv(r'C:/Users/notebook/OneDrive/Escritorio/Henry clase/Proyecto grupal OLIST/csv normalizados/SellersNor.csv', index =False, header=True)

In [ ]:
sellers

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,Mogi Guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,Rio De Janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,Sao Paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,Braganca Paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,Sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,Palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,Sao Paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,Pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,Taubate,SP

In [ ]:
product_category['product_category_name'] = product_category.product_category_name.str.title()
product_category['product_category_name_english'] = product_category.product_category_name_english.str.title()

#product_category.to_csv(r'C:/Users/notebook/OneDrive/Escritorio/Henry clase/Proyecto grupal OLIST/csv normalizados/Product_categoryNor.csv', index =False, header=True)

In [ ]:
product_category

            product_category_name product_category_name_english
0                    Beleza_Saude                 Health_Beauty
1          Informatica_Acessorios         Computers_Accessories
2                      Automotivo                          Auto
3                 Cama_Mesa_Banho                Bed_Bath_Table
4                Moveis_Decoracao               Furniture_Decor
..                            ...                           ...
66                         Flores                       Flowers
67             Artes_E_Artesanato         Arts_And_Craftmanship
68                Fraldas_Higiene           Diapers_And_Hygiene
69  Fashion_Roupa_Infanto_Juvenil     Fashion_Childrens_Clothes
70             Seguros_E_Servicos         Security_And_Services

[71 rows x 2 columns]

In [ ]:
closed_deals['won_date'] = closed_deals['won_date'].dt.date

closed_deals['won_date'] = pd.to_datetime(closed_deals['won_date'])

closed_deals.drop(columns='has_company',inplace=True)
closed_deals.drop(columns='has_gtin',inplace=True)
closed_deals.drop(columns='average_stock',inplace=True)
closed_deals.drop(columns='declared_product_catalog_size',inplace=True)

closed_deals["business_segment"].fillna("Sin Dato", inplace=True)
closed_deals["lead_type"].fillna("Sin Dato", inplace=True)
closed_deals["lead_behaviour_profile"].fillna("Sin Dato", inplace=True)
closed_deals["business_type"].fillna("Sin Dato", inplace=True)

#closed_deals.to_csv(r'C:/Users/notebook/OneDrive/Escritorio/Henry clase/Proyecto grupal OLIST/csv normalizados/Closed_dealsNor.csv', index =False, header=True)

In [ ]:
marketing_q['origin'] = marketing_q.origin.str.title()

marketing_q["origin"].fillna("Sin Dato", inplace=True)

#marketing_q.to_csv(r'C:/Users/notebook/OneDrive/Escritorio/Henry clase/Proyecto grupal OLIST/csv normalizados/MarketingNor.csv', index =False, header=True)